# Generated by Django 5.2.13 on 2026-04-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_disease_name', models.CharField(max_length=100, unique=True)),
                ('plant_disease_solution', models.TextField()),
            ],
        ),
    ]
